[application]
name = "Steven Wing - Portfolio"
default_platform = "web"
out_dir = "dist"


[web.app]
title = "Steven Wing - Portfolio"

[bundle]
identifier = "dev.stevenwing.portfolio"
publisher = "Steven Wing"